name: TeddyCloud
version: aa648b5
slug: teddycloud
description: An alternative server for your Toniebox
url: https://github.com/mrueg/addon-teddycloud
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:teddy-bear
image: ghcr.io/mrueg/teddycloud/{arch}
arch:
- aarch64
- amd64
- armv7
init: false
hassio_api: true
host_network: true
privileged:
- NET_ADMIN
- NET_RAW
ports:
  80/tcp: null
  443/tcp: 443
  8443/tcp: null
ports_description:
  80/tcp: TeddyCloud Web Interface (http)
  443/tcp: TeddyCloud API
  8443/tcp: TeddyCloud Web Interface (https)
map:
- addon_config:rw
