channel: edge
addons:
  teddycloud:
    repository: mrueg/addon-teddycloud
    target: teddycloud
    image: ghcr.io/mrueg/teddycloud/{arch}
  standalone-chromium:
    repository: mrueg/addon-standalone-chromium
    target: standalone-chromium
    image: ghcr.io/mrueg/standalone-chromium/{arch}
